Repository project-studying-dotnet/Streetcode-Admin-March-01, pull requests merged in 2024-04, with the labels that each got.

#136 Apply Action Filter and FluentValidation for validation
  Streetcode/Streetcode.BLL/ActionFilters/ModelStateFilter.cs
  Streetcode/Streetcode.BLL/MediatR/Streetcode/Fact/Create/CreateFactDtoValidator.cs
  Streetcode/Streetcode.BLL/Streetcode.BLL.csproj
  Streetcode/Streetcode.WebApi/Extensions/ServiceCollectionExtensions.cs
  Streetcode/Streetcode.WebApi/Program.cs
Labels: enhancement

#130 Delete Source functionality
  Streetcode/Streetcode.BLL/MediatR/Sources/SourceLinkCategory/Delete/DeleteCategoryCommand.cs
  Streetcode/Streetcode.BLL/MediatR/Sources/SourceLinkCategory/Delete/DeleteCategoryHandler.cs
  Streetcode/Streetcode.WebApi/Controllers/Source/SourcesController.cs
  Streetcode/Streetcode.XUnitTest/MediatRTests/Sources/DeleteCategoryHandlerTests.cs
Labels: enhancement

#138 tests_Get_Partner_By_Id
  Streetcode/Streetcode.XUnitTest/MediatRTests/Partners/GetPartnerByIdTests.cs
Labels: test

#90 Implement Create functionality for Sources block
  Streetcode/Streetcode.BLL/DTO/Sources/CreateCategoryRequestDto.cs
  Streetcode/Streetcode.BLL/DTO/Sources/SourceLinkCategoryDTO.cs
  Streetcode/Streetcode.BLL/Mapping/Sources/SourceLinkCategoryProfile.cs
  Streetcode/Streetcode.BLL/MediatR/Sources/SourceLinkCategory/Create/CreateCategoryCommand.cs
  Streetcode/Streetcode.BLL/MediatR/Sources/SourceLinkCategory/Create/CreateCategoryHandler.cs
  Streetcode/Streetcode.BLL/MediatR/Sources/SourceLinkCategory/Create/CreateCategoryRequestDtoValidator.cs
  Streetcode/Streetcode.DAL/Entities/Sources/StreetcodeCategoryContent.cs
  Streetcode/Streetcode.WebApi/Controllers/Source/SourcesController.cs
  Streetcode/Streetcode.XUnitTest/Streetcode.XUnitTest.csproj
Labels: story feature

#143 Implement global (controller) filter for checking
  Streetcode/Streetcode.BLL/ActionFilters/AsyncValidateEntityExistsFilter.cs
  Streetcode/Streetcode.BLL/Mapping/Streetcode/TextContent/FactProfile.cs
  Streetcode/Streetcode.DAL/Contracts/IEntity.cs
  Streetcode/Streetcode.DAL/Entities/Streetcode/TextContent/Fact.cs
  Streetcode/Streetcode.DAL/Repositories/Interfaces/Base/IEntityRepositoryBase.cs
  Streetcode/Streetcode.DAL/Repositories/Realizations/Base/EntityRepositoryBase.cs
  Streetcode/Streetcode.WebApi/Controllers/Streetcode/TextContent/FactController.cs
  Streetcode/Streetcode.WebApi/Extensions/ServiceCollectionExtensions.cs
Labels: enhancement

#148 unit tests for CreateCategoryHandler
  Streetcode/Streetcode.BLL/MediatR/Sources/SourceLinkCategory/Create/CreateCategoryHandler.cs
  Streetcode/Streetcode.XUnitTest/MediatRTests/Sources/CreateCategoryHandlerTests.cs
  Streetcode/Streetcode.XUnitTest/Streetcode.XUnitTest.csproj
Labels: test

#142 feat/79: add CategoryContentUpdateDto, mapping, put action, handler, command
  Streetcode/Streetcode.BLL/DTO/Sources/CategoryContentUpdateDTO.cs
  Streetcode/Streetcode.BLL/Mapping/Sources/StreetcodeCategoryContentProfile.cs
  Streetcode/Streetcode.BLL/MediatR/Sources/SourceLinkCategory/Update/UpdateCategoryContentCommand.cs
  Streetcode/Streetcode.BLL/MediatR/Sources/SourceLinkCategory/Update/UpdateCategoryContentHandler.cs
  Streetcode/Streetcode.BLL/MediatR/Sources/SourceLinkCategory/Update/UpdateCategoryContentValidator.cs
  Streetcode/Streetcode.WebApi/Controllers/Source/SourcesController.cs
Labels: enhancement

#173 test/169: add tests
  Streetcode/Streetcode.XUnitTest/MediatRTests/Sources/UpdateCategoryContentHandlerTests.cs
Labels: test

#180 Feat - history map create logic
  Streetcode/Streetcode.BLL/DTO/StreetcodeToponym/CreateStreetcodeToponymRequestDto.cs
  Streetcode/Streetcode.BLL/DTO/StreetcodeToponym/CreateStreetcodeToponymResponseDto.cs
  Streetcode/Streetcode.BLL/Mapping/Toponyms/StreetcodeToponymProfile.cs
  Streetcode/Streetcode.BLL/MediatR/StreetcodeToponym/Create/CreateStreetcodeToponymCommand.cs
  Streetcode/Streetcode.BLL/MediatR/StreetcodeToponym/Create/CreateStreetcodeToponymHandler.cs
  Streetcode/Streetcode.BLL/MediatR/StreetcodeToponym/Create/CreateStreetcodeToponymRequestDtoValidator.cs
  Streetcode/Streetcode.BLL/Resources/Errors/ErrorMessages.Designer.cs
  Streetcode/Streetcode.BLL/Resources/Errors/ErrorMessages.resx
  Streetcode/Streetcode.WebApi/Controllers/Toponyms/StreetcodeToponymController.cs
  Streetcode/Streetcode.XUnitTest/MediatRTests/StreetcodeToponym/CreateStreetcodeToponymHandlerTests.cs
  Streetcode/Streetcode.XUnitTest/ValidationTests/StreetcodeToponym/CreateStreetcodeToponymRequestDtoValidatorTests.cs
Labels: story feature

#185 Add Team/GetAllMain, GetAll, GetById Hadlers Tests
  Streetcode/Streetcode.BLL/MediatR/Team/GetAll/GetAllTeamHandler.cs
  Streetcode/Streetcode.BLL/MediatR/Team/GetAllMain/GetAllMainTeamHandler.cs
  Streetcode/Streetcode.BLL/MediatR/Team/GetById/GetByIdTeamHandler.cs
  Streetcode/Streetcode.XUnitTest/MediatRTests/Team/GetAllMainTeamHandlerTests.cs
  Streetcode/Streetcode.XUnitTest/MediatRTests/Team/GetAllTeamHandlerTests.cs
  Streetcode/Streetcode.XUnitTest/MediatRTests/Team/GetByIdTeamHandlerTests.cs
Labels: test

#188 fix bug and error messages in Timeline folder
  Streetcode/Streetcode.BLL/MediatR/Timeline/HistoricalContext/GetAll/GetAllHistoricalContextHandler.cs
  Streetcode/Streetcode.BLL/MediatR/Timeline/TimelineItem/GetAll/GetAllTimelineItemsHandler.cs
  Streetcode/Streetcode.BLL/MediatR/Timeline/TimelineItem/GetById/GetTimelineItemByIdHandler.cs
Labels: bug

#187 History Map - Delete logic
  Streetcode/Streetcode.BLL/DTO/StreetcodeToponym/DeleteStreetcodeToponymRequestDto.cs
  Streetcode/Streetcode.BLL/DTO/StreetcodeToponym/DeleteStreetcodeToponymResponseDto.cs
  Streetcode/Streetcode.BLL/MediatR/StreetcodeToponym/Create/CreateStreetcodeToponymHandler.cs
  Streetcode/Streetcode.BLL/MediatR/StreetcodeToponym/Delete/DeleteStreetcodeToponymCommand.cs
  Streetcode/Streetcode.BLL/MediatR/StreetcodeToponym/Delete/DeleteStreetcodeToponymHandler.cs
  Streetcode/Streetcode.BLL/MediatR/StreetcodeToponym/Delete/DeleteStreetcodeToponymRequestDtoValidator.cs
  Streetcode/Streetcode.BLL/Resources/Errors/ErrorMessages.Designer.cs
  Streetcode/Streetcode.BLL/Resources/Errors/ErrorMessages.resx
  Streetcode/Streetcode.WebApi/Controllers/Toponyms/StreetcodeToponymController.cs
  Streetcode/Streetcode.XUnitTest/MediatRTests/StreetcodeToponym/CreateStreetcodeToponymHandlerTests.cs
  Streetcode/Streetcode.XUnitTest/MediatRTests/StreetcodeToponym/DeleteStreetcodeToponymHandlerTests.cs
  Streetcode/Streetcode.XUnitTest/ValidationTests/StreetcodeToponym/DeleteStreetcodeToponymRequestDtoValidatorTests.cs
Labels: story feature

#181 Add CreateFactDtoValidatorTests and UpdateFactDtoValidatorTests
  Streetcode/Streetcode.BLL/DTO/Streetcode/TextContent/Fact/CreateFactDTO.cs
  Streetcode/Streetcode.BLL/DTO/Streetcode/TextContent/Fact/UpdateFactDto.cs
  Streetcode/Streetcode.BLL/MediatR/Streetcode/Fact/Create/CreateFactDtoValidator.cs
  Streetcode/Streetcode.BLL/MediatR/Streetcode/Fact/Update/UpdateFactDtoValidator.cs
  Streetcode/Streetcode.XUnitTest/ValidationTests/Streetcode/Fact/CreateFactDtoValidatorTests.cs
  Streetcode/Streetcode.XUnitTest/ValidationTests/Streetcode/Fact/UpdateFactDtoValidatorTests.cs
Labels: test

#184 Add UpdateCategoryContentValidatorTests
  Streetcode/Streetcode.BLL/MediatR/Sources/SourceLinkCategory/Update/UpdateCategoryContentValidator.cs
  Streetcode/Streetcode.XUnitTest/ValidationTests/Sources/UpdateCategoryContentValidatorTests.cs
Labels: test

#182 Feat/create art in gallery v2
  Streetcode/Streetcode.BLL/DTO/Media/Art/CreateArtRequestDto.cs
  Streetcode/Streetcode.BLL/DTO/Media/Art/CreateArtResponseDto.cs
  Streetcode/Streetcode.BLL/Mapping/Media/Images/ArtProfile.cs
  Streetcode/Streetcode.BLL/MediatR/Media/Art/Create/CreateArtCommand.cs
  Streetcode/Streetcode.BLL/MediatR/Media/Art/Create/CreateArtHandler.cs
  Streetcode/Streetcode.BLL/MediatR/Media/Art/Create/CreateArtRequestDtoValidator.cs
  Streetcode/Streetcode.WebApi/Controllers/Media/Images/ArtController.cs
  Streetcode/Streetcode.XUnitTest/MediatRTests/Media/Art/CreateArtHandlerTests.cs
  Streetcode/Streetcode.XUnitTest/ValidationTests/Media/Art/CreateArtRequestDtoValidatorTests.cs
Labels: story feature

#190 Add GetAllTerms, GetTermById HandlerTests
  Streetcode/Streetcode.BLL/MediatR/Streetcode/Term/GetAll/GetAllTermsHandler.cs
  Streetcode/Streetcode.BLL/MediatR/Streetcode/Term/GetById/GetTermByIdHandler.cs
  Streetcode/Streetcode.XUnitTest/MediatRTests/StreetCode/Term/GetAllTermsHandlerTests.cs
  Streetcode/Streetcode.XUnitTest/MediatRTests/StreetCode/Term/GetTermByIdHandlerTests.cs
Labels: test

#174 feat/158: implement delete art
  Streetcode/Streetcode.BLL/DTO/Media/Art/DeleteStreetcodeArtRequestDto.cs
  Streetcode/Streetcode.BLL/DTO/Media/Art/DeleteStreetcodeArtResponseDTO.cs
  Streetcode/Streetcode.BLL/MediatR/Media/StreetcodeArt/Delete/DeleteStreetcodeArtCommand.cs
  Streetcode/Streetcode.BLL/MediatR/Media/StreetcodeArt/Delete/DeleteStreetcodeArtHandler.cs
  Streetcode/Streetcode.BLL/MediatR/Media/StreetcodeArt/Delete/DeleteStreetcodeArtRequestDtoValidator.cs
  Streetcode/Streetcode.BLL/Resources/Errors/ErrorMessages.Designer.cs
  Streetcode/Streetcode.BLL/Resources/Errors/ErrorMessages.resx
  Streetcode/Streetcode.WebApi/Controllers/Media/Images/StreetcodeArtController.cs
  Streetcode/Streetcode.XUnitTest/MediatRTests/Media/Art/CreateArtHandlerTests.cs
  Streetcode/Streetcode.XUnitTest/MediatRTests/Media/StreetcodeArt/DeleteStreetcodeArtHandlerTest.cs
  Streetcode/Streetcode.XUnitTest/ValidationTests/Media/StreetcodeArt/DeleteStreetcodeArtRequestDtoValidatorTests.cs
Labels: story feature

#179 Feat/159/add delete logic for chronology block
  Streetcode/Streetcode.BLL/MediatR/Timeline/TimelineItem/Delete/DeleteTimelineItemCommand.cs
  Streetcode/Streetcode.BLL/MediatR/Timeline/TimelineItem/Delete/DeleteTimelineItemHandler.cs
  Streetcode/Streetcode.WebApi/Controllers/Timeline/TimelineItemController.cs
  Streetcode/Streetcode.XUnitTest/MediatRTests/Timeline/TimelineItem/DeleteTimelineItemHandlerTests.cs
Labels: story feature

#200 Add Create logic for Video block
  Streetcode/Streetcode.BLL/DTO/Media/Video/CreateVideoRequestDto.cs
  Streetcode/Streetcode.BLL/Mapping/Media/VideoProfile.cs
  Streetcode/Streetcode.BLL/MediatR/Media/Video/Create/CreateVideoCommand.cs
  Streetcode/Streetcode.BLL/MediatR/Media/Video/Create/CreateVideoHandler.cs
  Streetcode/Streetcode.BLL/MediatR/Media/Video/Create/CreateVideoRequestDtoValidator.cs
  Streetcode/Streetcode.WebApi/Controllers/Media/VideoController.cs
  Streetcode/Streetcode.XUnitTest/MediatRTests/Media/Video/CreateVideoHandlerTests.cs
  Streetcode/Streetcode.XUnitTest/ValidationTests/Media/Video/CreateVideoRequestDtoValidatorTests.cs
Labels: story feature

#212 Fix/210/history map add create and delete logic to streetcode coordinate
  Streetcode/Streetcode.BLL/DTO/AdditionalContent/Coordinates/Types/CreateStreetcodeCoordinateRequestDto.cs
  Streetcode/Streetcode.BLL/DTO/AdditionalContent/Coordinates/Types/CreateStreetcodeCoordinateResponseDto.cs
  Streetcode/Streetcode.BLL/DTO/AdditionalContent/Coordinates/Types/DeleteStreetcodeCoordinateRequestDto.cs
  Streetcode/Streetcode.BLL/DTO/AdditionalContent/Coordinates/Types/DeleteStreetcodeCoordinateResponseDto.cs
  Streetcode/Streetcode.BLL/Mapping/AdditionalContent/Coordinates/StreetcodeCoordinateProfile.cs
  Streetcode/Streetcode.BLL/MediatR/AdditionalContent/StreetcodeCoordinate/Create/CreateStreetcodeCoordinateCommand.cs
  Streetcode/Streetcode.BLL/MediatR/AdditionalContent/StreetcodeCoordinate/Create/CreateStreetcodeCoordinateHandler.cs
  Streetcode/Streetcode.BLL/MediatR/AdditionalContent/StreetcodeCoordinate/Create/CreateStreetcodeCoordinateRequestDtoValidator.cs
  Streetcode/Streetcode.BLL/MediatR/AdditionalContent/StreetcodeCoordinate/Delete/DeleteStreetcodeCoordinateCommand.cs
  Streetcode/Streetcode.BLL/MediatR/AdditionalContent/StreetcodeCoordinate/Delete/DeleteStreetcodeCoordinateHandler.cs
  Streetcode/Streetcode.BLL/MediatR/AdditionalContent/StreetcodeCoordinate/Delete/DeleteStreetcodeCoordinateRequestDtoValidator.cs
  Streetcode/Streetcode.WebApi/Controllers/AdditionalContent/StreetcodeCoordinateController.cs
  Streetcode/Streetcode.XUnitTest/MediatRTests/AdditionalContent/Coordinates/Types/CreateStreetcodeCoordinateHandlerTests.cs
  Streetcode/Streetcode.XUnitTest/MediatRTests/AdditionalContent/Coordinates/Types/DeleteStreetcodeCoordinateHandlerTests.cs
  Streetcode/Streetcode.XUnitTest/ValidationTests/AdditionalContent/Coordinates/Types/CreateStreetcodeCoordinateRequestDtoValidatorTests.cs
  Streetcode/Streetcode.XUnitTest/ValidationTests/AdditionalContent/Coordinates/Types/DeleteStreetcodeCoordinateRequestDtoValidatorTests.cs
Labels: story feature

#213 Feat/160/chronology block update timelineitem
  Streetcode/Streetcode.BLL/DTO/Timeline/CreateHistoricalContextRequestDto.cs
  Streetcode/Streetcode.BLL/DTO/Timeline/HistoricalContextDTO.cs
  Streetcode/Streetcode.BLL/DTO/Timeline/TimelineItemDTO.cs
  Streetcode/Streetcode.BLL/DTO/Timeline/UpdateTimelineItemRequestDto.cs
  Streetcode/Streetcode.BLL/Mapping/Timeline/TimelineItemProfile.cs
  Streetcode/Streetcode.BLL/MediatR/Timeline/TimelineItem/Update/UpdateTimelineItemCommand.cs
  Streetcode/Streetcode.BLL/MediatR/Timeline/TimelineItem/Update/UpdateTimelineItemHandler.cs
  Streetcode/Streetcode.BLL/MediatR/Timeline/TimelineItem/Update/UpdateTimelineItemRequestDtoValidator.cs
  Streetcode/Streetcode.DAL/Enums/DateViewPattern.cs
  Streetcode/Streetcode.WebApi/Controllers/Timeline/TimelineItemController.cs
  Streetcode/Streetcode.XUnitTest/ValidationTests/Timeline/UpdateTimelineItemRequestDtoValidatorTests.cs
Labels: story feature

#211 feat/209: create delete art
  Streetcode/Streetcode.BLL/DTO/Media/Art/DeleteArtRequestDto.cs
  Streetcode/Streetcode.BLL/DTO/Media/Art/DeleteArtResponseDto.cs
  Streetcode/Streetcode.BLL/DTO/Media/Art/DeleteStreetcodeArtRequestDto.cs
  Streetcode/Streetcode.BLL/DTO/Media/Art/DeleteStreetcodeArtResponseDTO.cs
  Streetcode/Streetcode.BLL/MediatR/Media/Art/Delete/DeleteArtCommand.cs
  Streetcode/Streetcode.BLL/MediatR/Media/Art/Delete/DeleteArtHandler.cs
  Streetcode/Streetcode.BLL/MediatR/Media/Art/Delete/DeleteArtRequestDtoValidator.cs
  Streetcode/Streetcode.WebApi/Controllers/Media/Images/ArtController.cs
  Streetcode/Streetcode.XUnitTest/MediatRTests/Media/Art/DeleteArtHandlerTest.cs
  Streetcode/Streetcode.XUnitTest/ValidationTests/Media/Art/DeleteArtRequestDtoValidatorTests.cs
Labels: story feature

#215 History Map - Add Create and Delete logic to StatisticRecord
  Streetcode/Streetcode.BLL/DTO/Analytics/StatisticRecord/CreateStatisticRecordRequestDto.cs
  Streetcode/Streetcode.BLL/DTO/Analytics/StatisticRecord/CreateStatisticRecordResponseDto.cs
  Streetcode/Streetcode.BLL/DTO/Analytics/StatisticRecord/DeleteStatisticRecordRequestDto.cs
  Streetcode/Streetcode.BLL/DTO/Analytics/StatisticRecord/DeleteStatisticRecordResponseDto.cs
  Streetcode/Streetcode.BLL/Mapping/Analytics/StatisticRecordProfile.cs
  Streetcode/Streetcode.BLL/MediatR/Analytics/StatisticRecord/Create/CreateStatisticRecordCommand.cs
  Streetcode/Streetcode.BLL/MediatR/Analytics/StatisticRecord/Create/CreateStatisticRecordHandler.cs
  Streetcode/Streetcode.BLL/MediatR/Analytics/StatisticRecord/Create/CreateStatisticRecordRequestDtoValidator.cs
  Streetcode/Streetcode.BLL/MediatR/Analytics/StatisticRecord/Delete/DeleteStatisticRecordCommand.cs
  Streetcode/Streetcode.BLL/MediatR/Analytics/StatisticRecord/Delete/DeleteStatisticRecordHandler.cs
  Streetcode/Streetcode.BLL/MediatR/Analytics/StatisticRecord/Delete/DeleteStatisticRecordRequestDtoValidator.cs
  Streetcode/Streetcode.BLL/Resources/Errors/ErrorMessages.Designer.cs
  Streetcode/Streetcode.BLL/Resources/Errors/ErrorMessages.resx
  Streetcode/Streetcode.BLL/Streetcode.BLL.csproj
  Streetcode/Streetcode.WebApi/Controllers/Analytics/StatisticRecordController.cs
  Streetcode/Streetcode.WebApi/Streetcode.WebApi.csproj
  Streetcode/Streetcode.XUnitTest/MediatRTests/Analytics/StatisticRecord/CreateStatisticRecordHandlerTests.cs
  Streetcode/Streetcode.XUnitTest/MediatRTests/Analytics/StatisticRecord/DeleteStatisticRecordHandlerTests.cs
  Streetcode/Streetcode.XUnitTest/ValidationTests/Analytics/StatisticRecord/CreateStatisticRecordRequestDtoValidatorTests.cs
  Streetcode/Streetcode.XUnitTest/ValidationTests/Analytics/StatisticRecord/DeleteStatisticRecordRequestDtoValidatorTests.cs
Labels: story feature

#221 Fix/216/refactor to reduce cognitive complexity
  Streetcode/Streetcode.WebApi/Utils/WebParsingUtils.cs
  Streetcode/Streetcode.XUnitTest/Streetcode.XUnitTest.csproj
  Streetcode/Streetcode.XUnitTest/Utils/WebParsingUtilsTests.cs
Labels: code smell

#231 Implemented Create logic for text block with tests for it
  Streetcode/Streetcode.BLL/DTO/Streetcode/TextContent/Text/CreateTextRequestDto.cs
  Streetcode/Streetcode.BLL/DTO/Streetcode/TextContent/Text/CreateTextResponseDto.cs
  Streetcode/Streetcode.BLL/Mapping/Streetcode/TextContent/TextProfile.cs
  Streetcode/Streetcode.BLL/MediatR/Streetcode/Text/Create/CreateTextCommand.cs
  Streetcode/Streetcode.BLL/MediatR/Streetcode/Text/Create/CreateTextHandler.cs
  Streetcode/Streetcode.BLL/MediatR/Streetcode/Text/Create/CreateTextRequestDtoValidator.cs
  Streetcode/Streetcode.WebApi/Controllers/Streetcode/TextContent/TextController.cs
  Streetcode/Streetcode.XUnitTest/MediatRTests/StreetCode/Text/CreateTextHandlerTests.cs
  Streetcode/Streetcode.XUnitTest/ValidationTests/Streetcode/Text/CreateTextRequestDtoValidatorTests.cs
Labels: story feature

#222 test/214 unit tests for UpdateTimelineItemHandler
  Streetcode/Streetcode.XUnitTest/MediatRTests/Timeline/TimelineItem/UpdateTimelineItemHandlerTests.cs
Labels: test

#233 Implemented Update logic for text block with tests for it
  Streetcode/Streetcode.BLL/DTO/Streetcode/TextContent/Text/UpdateTextRequestDto.cs
  Streetcode/Streetcode.BLL/DTO/Streetcode/TextContent/Text/UpdateTextResponseDto.cs
  Streetcode/Streetcode.BLL/Mapping/Streetcode/TextContent/TextProfile.cs
  Streetcode/Streetcode.BLL/MediatR/Streetcode/Text/Update/UpdateTextCommand.cs
  Streetcode/Streetcode.BLL/MediatR/Streetcode/Text/Update/UpdateTextHandler.cs
  Streetcode/Streetcode.BLL/MediatR/Streetcode/Text/Update/UpdateTextRequestDtoValidator.cs
  Streetcode/Streetcode.WebApi/Controllers/Streetcode/TextContent/TextController.cs
  Streetcode/Streetcode.XUnitTest/MediatRTests/StreetCode/Text/UpdateTextHandlerTests.cs
  Streetcode/Streetcode.XUnitTest/ValidationTests/Streetcode/Text/UpdateTextRequestDtoTests.cs
Labels: story feature

#234 Implemented Delete logic for text block with tests for it
  Streetcode/Streetcode.BLL/DTO/Streetcode/TextContent/Text/DeleteTextRequestDto.cs
  Streetcode/Streetcode.BLL/DTO/Streetcode/TextContent/Text/DeleteTextResponseDto.cs
  Streetcode/Streetcode.BLL/MediatR/Streetcode/Text/Delete/DeleteTextCommand.cs
  Streetcode/Streetcode.BLL/MediatR/Streetcode/Text/Delete/DeleteTextHandler.cs
  Streetcode/Streetcode.BLL/MediatR/Streetcode/Text/Delete/DeleteTextRequestDtoValidator.cs
  Streetcode/Streetcode.WebApi/Controllers/Streetcode/TextContent/TextController.cs
  Streetcode/Streetcode.XUnitTest/MediatRTests/StreetCode/Text/DeleteTextHandlerTests.cs
  Streetcode/Streetcode.XUnitTest/ValidationTests/Streetcode/Text/DeleteTextRequestDtoValidatorTests.cs
Labels: story feature

#230 Feat/161/chronology block create timelineitem
  Streetcode/Streetcode.BLL/DTO/Timeline/CreateTimelineItemRequestDTO.cs
  Streetcode/Streetcode.BLL/DTO/Timeline/HistoricalContextDTO.cs
  Streetcode/Streetcode.BLL/Mapping/Timeline/TimelineItemProfile.cs
  Streetcode/Streetcode.BLL/MediatR/Timeline/TimelineItem/Create/CreateTimelineItemCommand.cs
  Streetcode/Streetcode.BLL/MediatR/Timeline/TimelineItem/Create/CreateTimelineItemHandler.cs
  Streetcode/Streetcode.BLL/MediatR/Timeline/TimelineItem/Create/CreateTimelineItemRequestDtoValidator.cs
  Streetcode/Streetcode.WebApi/Controllers/Timeline/TimelineItemController.cs
  Streetcode/Streetcode.XUnitTest/MediatRTests/Timeline/TimelineItem/CreateTimelineItemHandlerTests.cs
Labels: story feature

#238 Implemented Preview logic for text block with tests for it
  Streetcode/Streetcode.BLL/DTO/Streetcode/TextContent/Text/PreviewTextRequestDto.cs
  Streetcode/Streetcode.BLL/DTO/Streetcode/TextContent/Text/PreviewTextResponseDto.cs
  Streetcode/Streetcode.BLL/MediatR/Streetcode/Text/Preview/PreviewTextHandler.cs
  Streetcode/Streetcode.BLL/MediatR/Streetcode/Text/Preview/PreviewTextQuery.cs
  Streetcode/Streetcode.BLL/MediatR/Streetcode/Text/Preview/PreviewTextRequestDtoValidator.cs
  Streetcode/Streetcode.WebApi/Controllers/Streetcode/TextContent/TextController.cs
  Streetcode/Streetcode.XUnitTest/MediatRTests/StreetCode/Text/CreateTextHandlerTests.cs
  Streetcode/Streetcode.XUnitTest/MediatRTests/StreetCode/Text/PreviewTextHandlerTests.cs
  Streetcode/Streetcode.XUnitTest/ValidationTests/Streetcode/Text/PreviewTextRequestDtoValidatorTests.cs
  Streetcode/Streetcode.XUnitTest/ValidationTests/Streetcode/Text/UpdateTextRequestDtoValidatorTests.cs
Labels: story feature

#244 Add Delete logic to Video block and tests. Rename Utils folder to Uti…
  Streetcode/Streetcode.BLL/DTO/Media/Video/DeleteVideoRequestDto.cs
  Streetcode/Streetcode.BLL/DTO/Media/Video/DeleteVideoResponseDto.cs.cs
  Streetcode/Streetcode.BLL/MediatR/Media/Video/Delete/DeleteVideoCommand.cs
  Streetcode/Streetcode.BLL/MediatR/Media/Video/Delete/DeleteVideoHandler.cs
  Streetcode/Streetcode.BLL/MediatR/Media/Video/Delete/DeleteVideoRequestDtoValidator.cs
  Streetcode/Streetcode.WebApi/Controllers/Media/VideoController.cs
  Streetcode/Streetcode.XUnitTest/MediatRTests/Media/Video/DeleteVideoHandlerTests.cs
  Streetcode/Streetcode.XUnitTest/UtilsTests/WebParsingUtilsTests.cs
  Streetcode/Streetcode.XUnitTest/ValidationTests/Media/Video/DeleteVideoRequestDtoValidatorTests.cs
Labels: test, story feature

#251 Fix Handler in Preview logic for text block
  Streetcode/Streetcode.BLL/MediatR/Streetcode/Text/Preview/PreviewTextHandler.cs
Labels: code smell, story feature

#255 Implemented Update logic for Term block with tests for it
  Streetcode/Streetcode.BLL/DTO/Streetcode/TextContent/Term/UpdateTermRequestDto.cs
  Streetcode/Streetcode.BLL/DTO/Streetcode/TextContent/Term/UpdateTermResponseDto.cs
  Streetcode/Streetcode.BLL/Mapping/Streetcode/TextContent/TermProfile.cs
  Streetcode/Streetcode.BLL/MediatR/Streetcode/Term/Update/UpdateTermCommand.cs
  Streetcode/Streetcode.BLL/MediatR/Streetcode/Term/Update/UpdateTermHandler.cs
  Streetcode/Streetcode.BLL/MediatR/Streetcode/Term/Update/UpdateTermRequestDtoValidator.cs
  Streetcode/Streetcode.WebApi/Controllers/Streetcode/TextContent/TermController.cs
  Streetcode/Streetcode.XUnitTest/MediatRTests/StreetCode/Term/UpdateTermHandlerTests.cs
  Streetcode/Streetcode.XUnitTest/ValidationTests/Streetcode/Term/UpdateTermRequestDtoValidatorTests.cs
Labels: story feature

#254 add login endpoint
  Streetcode/Streetcode.BLL/DTO/Account/LoginUserDTO.cs
  Streetcode/Streetcode.BLL/DTO/Account/Validation/LoginUserDtoValidator.cs
  Streetcode/Streetcode.WebApi/Controllers/Account/AccountController.cs
Labels: story feature

#258 add logout endpoint
  Streetcode/Streetcode.WebApi/Controllers/Account/AccountController.cs
Labels: story feature

#259 Implemented Delete logic for Term block with tests for it
  Streetcode/Streetcode.BLL/DTO/Streetcode/TextContent/Term/DeleteTermRequestDto.cs
  Streetcode/Streetcode.BLL/DTO/Streetcode/TextContent/Term/DeleteTermResponseDto.cs
  Streetcode/Streetcode.BLL/Mapping/Streetcode/TextContent/TermProfile.cs
  Streetcode/Streetcode.BLL/MediatR/Streetcode/Term/Delete/DeleteTermCommand.cs
  Streetcode/Streetcode.BLL/MediatR/Streetcode/Term/Delete/DeleteTermHandler.cs
  Streetcode/Streetcode.BLL/MediatR/Streetcode/Term/Delete/DeleteTermRequestDtoValidator.cs
  Streetcode/Streetcode.WebApi/Controllers/Streetcode/TextContent/TermController.cs
  Streetcode/Streetcode.XUnitTest/MediatRTests/StreetCode/Term/DeleteTermHandlerTests.cs
  Streetcode/Streetcode.XUnitTest/ValidationTests/Streetcode/Term/DeleteTermRequestDtoValidatorTests.cs
Labels: story feature

#267 Fixed Code Smells like Member does not access instance data and can be marked as static
  Streetcode/Streetcode.WebApi/Middlewares/ExceptionMiddleware.cs
  Streetcode/Streetcode.XUnitTest/MediatRTests/Media/Art/DeleteArtHandlerTest.cs
  Streetcode/Streetcode.XUnitTest/MediatRTests/Media/StreetcodeArt/DeleteStreetcodeArtHandlerTest.cs
  Streetcode/Streetcode.XUnitTest/MediatRTests/Media/Video/CreateVideoHandlerTests.cs
  Streetcode/Streetcode.XUnitTest/MediatRTests/Sources/UpdateCategoryContentHandlerTests.cs
  Streetcode/Streetcode.XUnitTest/MediatRTests/StreetCode/Fact/UpdateFactHandlerTests.cs
Labels: code smell, story feature

#265 Renamed vars and test methods, deleted redundant parameters in methods of Text, Term, StreetcodeCoordinate and StatisticRecord blocks
  Streetcode/Streetcode.XUnitTest/MediatRTests/AdditionalContent/Coordinates/Types/DeleteStreetcodeCoordinateHandlerTests.cs
  Streetcode/Streetcode.XUnitTest/MediatRTests/Analytics/StatisticRecord/DeleteStatisticRecordHandlerTests.cs
  Streetcode/Streetcode.XUnitTest/MediatRTests/StreetCode/Term/CreateTermHandlerTests.cs
  Streetcode/Streetcode.XUnitTest/MediatRTests/StreetCode/Term/DeleteTermHandlerTests.cs
  Streetcode/Streetcode.XUnitTest/MediatRTests/StreetCode/Text/DeleteTextHandlerTests.cs
  Streetcode/Streetcode.XUnitTest/ValidationTests/Streetcode/Term/CreateTermRequestDtoValidatorTests.cs
  Streetcode/Streetcode.XUnitTest/ValidationTests/Streetcode/Term/UpdateTermRequestDtoValidatorTests.cs
Labels: code smell, story feature

#261 Fixed Term block Update logic - merged if statement with the enclosing one in Handler.
  Streetcode/Streetcode.BLL/MediatR/Streetcode/Term/Update/UpdateTermHandler.cs
Labels: code smell, story feature

#270 add RegisterUserDtoValidatorTests
  Streetcode/Streetcode.XUnitTest/ValidationTests/Account/RegisterUserDtoValidatorTests.cs
  Streetcode/Streetcode.XUnitTest/ValidationTests/Timeline/UpdateTimelineItemRequestDtoValidatorTests.cs
Labels: test, story feature

#268 Feat/263/improvement in seeding roles and seeding admin
  Streetcode/Streetcode.DAL/Entities/Users/ApplicationRole.cs
  Streetcode/Streetcode.DAL/Entities/Users/UserRole.cs
  Streetcode/Streetcode.DAL/Persistence/StreetcodeDbContext.cs
  Streetcode/Streetcode.WebApi/Controllers/Account/AccountController.cs
  Streetcode/Streetcode.WebApi/Extensions/ServiceProviderExtensions.cs
  Streetcode/Streetcode.WebApi/Program.cs
Labels: enhancement

#269 add jwt service
  Streetcode/Streetcode.BLL/DTO/Account/AuthenticationResponseDTO.cs
  Streetcode/Streetcode.BLL/Services/Users/TokenService.cs
  Streetcode/Streetcode.DAL/Entities/AdditionalContent/Jwt/JwtConfiguration.cs
  Streetcode/Streetcode.WebApi/Controllers/Account/AccountController.cs
  Streetcode/Streetcode.WebApi/Extensions/ServiceCollectionExtensions.cs
  Streetcode/Streetcode.WebApi/Program.cs
Labels: story feature

#272 move admin email to secrets.json
  Streetcode/Streetcode.WebApi/Extensions/ServiceProviderExtensions.cs
Labels: code smell, story feature

#279 Add CreateStreetcodeHandlerTests
  Streetcode/Streetcode.BLL/MediatR/Streetcode/Streetcode/Create/CreateStreetcodeHandler.cs
  Streetcode/Streetcode.XUnitTest/MediatRTests/StreetCode/StreetcodeTests/CreateStreetcodeHandlerTests.cs
Labels: test

#285 set access
  Streetcode/Streetcode.WebApi/Controllers/Account/AccountController.cs
  Streetcode/Streetcode.WebApi/Controllers/AdditionalContent/CoordinateController.cs
  Streetcode/Streetcode.WebApi/Controllers/AdditionalContent/StreetcodeCoordinateController.cs
  Streetcode/Streetcode.WebApi/Controllers/AdditionalContent/SubtitleController.cs
  Streetcode/Streetcode.WebApi/Controllers/AdditionalContent/TagController.cs
  Streetcode/Streetcode.WebApi/Controllers/Analytics/StatisticRecordController.cs
  Streetcode/Streetcode.WebApi/Controllers/Email/EmailController.cs
  Streetcode/Streetcode.WebApi/Controllers/Instagram/InstagramController.cs
  Streetcode/Streetcode.WebApi/Controllers/Media/AudioController.cs
  Streetcode/Streetcode.WebApi/Controllers/Media/VideoController.cs
  Streetcode/Streetcode.WebApi/Controllers/Partners/PartnersController.cs
  Streetcode/Streetcode.WebApi/Controllers/Payment/PaymentController.cs
  Streetcode/Streetcode.WebApi/Controllers/Source/SourcesController.cs
  Streetcode/Streetcode.WebApi/Controllers/Streetcode/RelatedFigureController.cs
  Streetcode/Streetcode.WebApi/Controllers/Streetcode/StreetcodeController.cs
  Streetcode/Streetcode.WebApi/Controllers/Streetcode/TextContent/FactController.cs
  Streetcode/Streetcode.WebApi/Controllers/Streetcode/TextContent/RelatedTermController.cs
  Streetcode/Streetcode.WebApi/Controllers/Streetcode/TextContent/TermController.cs
  Streetcode/Streetcode.WebApi/Controllers/Streetcode/TextContent/TextController.cs
  Streetcode/Streetcode.WebApi/Controllers/Team/PositionController.cs
  Streetcode/Streetcode.WebApi/Controllers/Team/TeamController.cs
  Streetcode/Streetcode.WebApi/Controllers/Team/TeamLinkController.cs
  Streetcode/Streetcode.WebApi/Controllers/Timeline/HistoricalContextController.cs
  Streetcode/Streetcode.WebApi/Controllers/Timeline/TimelineItemController.cs
  Streetcode/Streetcode.WebApi/Controllers/Toponyms/StreetcodeToponymController.cs
  Streetcode/Streetcode.WebApi/Controllers/Toponyms/ToponymController.cs
  Streetcode/Streetcode.WebApi/Controllers/Transactions/TransactLinksController.cs
  Streetcode/Streetcode.WebApi/Program.cs
Labels: story feature

#290 Feat/277/create background job to delete expired refresh tokens
  Streetcode/Streetcode.BLL/DTO/Account/LogoutUserDTO.cs
  Streetcode/Streetcode.BLL/DTO/Account/LogoutUserResponseDTO.cs
  Streetcode/Streetcode.BLL/MediatR/Account/GenerateNewAccessToken/GenerateNewAccessTokenHandler.cs
  Streetcode/Streetcode.BLL/MediatR/Account/Logout/LogoutUserCommand.cs
  Streetcode/Streetcode.BLL/MediatR/Account/Logout/LogoutUserDtoValidator.cs
  Streetcode/Streetcode.BLL/MediatR/Account/Logout/LogoutUserHandler.cs
  Streetcode/Streetcode.BLL/Services/BackgroundServices/DeleteExpiredRefreshTokensService.cs
  Streetcode/Streetcode.BLL/Services/Users/TokenService.cs
  Streetcode/Streetcode.WebApi/Controllers/Account/AccountController.cs
  Streetcode/Streetcode.WebApi/Program.cs
Labels: story feature

#292 fix mapping
  Streetcode/Streetcode.BLL/Mapping/Timeline/TimelineItemProfile.cs
Labels: wontfix

#295 add authorization for swagger
  Streetcode/Streetcode.BLL/Interfaces/Users/ITokenService.cs
  Streetcode/Streetcode.BLL/MediatR/Account/GenerateNewAccessToken/GenerateNewAccessTokenHandler.cs
  Streetcode/Streetcode.BLL/MediatR/Account/Login/LoginUserHandler.cs
  Streetcode/Streetcode.BLL/MediatR/Account/Register/RegisterUserHandler.cs
  Streetcode/Streetcode.BLL/Services/Users/TokenService.cs
  Streetcode/Streetcode.WebApi/Extensions/ServiceCollectionExtensions.cs
  Streetcode/Streetcode.WebApi/Program.cs
Labels: enhancement

#293 Feat/278/implement specification pattern
  Streetcode/Streetcode.BLL/MediatR/Timeline/TimelineItem/Create/CreateTimelineItemHandler.cs
  Streetcode/Streetcode.BLL/MediatR/Timeline/TimelineItem/Update/UpdateTimelineItemHandler.cs
  Streetcode/Streetcode.DAL/Repositories/Interfaces/Base/IRepositoryBase.cs
  Streetcode/Streetcode.DAL/Repositories/Realizations/Base/RepositoryBase.cs
  Streetcode/Streetcode.DAL/Specifications/TimelineSpecifications/HistoricalContextSpecs.cs
  Streetcode/Streetcode.DAL/Specifications/TimelineSpecifications/HistoricalContextTimelineSpecs.cs
  Streetcode/Streetcode.DAL/Specifications/TimelineSpecifications/TimelineItemSpecs.cs
  Streetcode/Streetcode.DAL/Streetcode.DAL.csproj
Labels: enhancement

#302 Test/299/unit tests for specifications
  Streetcode/Streetcode.XUnitTest/SpecificationTests/SpecificationBuilderExtensions_IncludeTests.cs
  Streetcode/Streetcode.XUnitTest/SpecificationTests/SpecificationBuilderExtensions_WhereTests.cs
Labels: test

#305 Fix/303/fix maintainability issues
  Streetcode/Streetcode.BLL/MediatR/Account/Logout/LogoutUserHandler.cs
  Streetcode/Streetcode.BLL/MediatR/Account/Register/RegisterUserHandler.cs
  Streetcode/Streetcode.WebApi/Controllers/Account/AccountController.cs
Labels: code smell

#304 refactor backround job
  Streetcode/Streetcode.BLL/Services/BackgroundServices/DeleteExpiredRefreshTokensService.cs
  Streetcode/Streetcode.WebApi/Program.cs
  Streetcode/Streetcode.WebApi/Utils/DeleteExpiredRefreshTokensUtils.cs
Labels: enhancement

#307 Implemented Create and Delete logic for Admin/Partners
  Streetcode/Streetcode.BLL/DTO/Partners/Create/CreatePartnerRequestDto.cs
  Streetcode/Streetcode.BLL/DTO/Partners/Create/CreatePartnerResponseDto.cs
  Streetcode/Streetcode.BLL/DTO/Partners/Create/CreatePartnerSourceLinkRequestDto.cs
  Streetcode/Streetcode.BLL/DTO/Partners/Create/CreatePartnerSourceLinkResponseDto.cs
  Streetcode/Streetcode.BLL/DTO/Partners/Delete/DeletePartnerRequestDto.cs
  Streetcode/Streetcode.BLL/DTO/Partners/Delete/DeletePartnerResponseDto.cs
  Streetcode/Streetcode.BLL/Mapping/Partners/PartnerProfile.cs
  Streetcode/Streetcode.BLL/Mapping/Partners/PartnerSourceLinkProfile.cs
  Streetcode/Streetcode.BLL/Mapping/Streetcode/StreetcodeProfile.cs
  Streetcode/Streetcode.BLL/MediatR/Partners/Create/CreatePartnerCommand.cs
  Streetcode/Streetcode.BLL/MediatR/Partners/Create/CreatePartnerHandler.cs
  Streetcode/Streetcode.BLL/MediatR/Partners/Create/CreatePartnerQuery.cs
  Streetcode/Streetcode.BLL/MediatR/Partners/Create/CreatePartnerRequestDtoValidator.cs
  Streetcode/Streetcode.BLL/MediatR/Partners/Create/CreatePartnerSourceLinkRequestDtoValidator.cs
  Streetcode/Streetcode.BLL/MediatR/Partners/Delete/DeletePartnerCommand.cs
  Streetcode/Streetcode.BLL/MediatR/Partners/Delete/DeletePartnerHandler.cs
  Streetcode/Streetcode.BLL/MediatR/Partners/Delete/DeletePartnerQuery.cs
  Streetcode/Streetcode.BLL/MediatR/Partners/Delete/DeletePartnerRequestDtoValidator.cs
  Streetcode/Streetcode.WebApi/Controllers/Partners/PartnersController.cs
  Streetcode/Streetcode.XUnitTest/MediatRTests/Partners/CreatePartnerHandlerTests.cs
  Streetcode/Streetcode.XUnitTest/MediatRTests/Partners/DeletePartnerHandlerTests.cs
  Streetcode/Streetcode.XUnitTest/ValidationTests/Partners/CreatePartnerRequestDtoValidatorTests.cs
  Streetcode/Streetcode.XUnitTest/ValidationTests/Partners/CreatePartnerSourceLinkRequestDtoValidatorTests.cs
  Streetcode/Streetcode.XUnitTest/ValidationTests/Partners/DeletePartnerRequestDtoValidatorTests.cs
Labels: story feature

#309 Fix/308/admin partner create logic added a check of the logo id for uniqueness
  Streetcode/Streetcode.BLL/MediatR/Analytics/StatisticRecord/Create/CreateStatisticRecordHandler.cs
  Streetcode/Streetcode.BLL/MediatR/Partners/Create/CreatePartnerHandler.cs
  Streetcode/Streetcode.XUnitTest/MediatRTests/Partners/CreatePartnerHandlerTests.cs
  Streetcode/Streetcode.XUnitTest/MediatRTests/Timeline/TimelineItem/CreateTimelineItemHandlerTests.cs
Labels: bug

#328 change to httpClientFactory
  Streetcode/Streetcode.WebApi/Program.cs
  Streetcode/Streetcode.WebApi/Utils/WebParsingUtils.cs
Labels: enhancement
